project:
  title: "Bee Project"
  output-dir: out

toc: true
number-sections: false
bibliography: references.bib  
echo: false
fig-align: center
lang: en-GB
format:
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
    keep-tex: true
    template-partials: 
      - title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}