project:
  title: "Bee Project"
  output-dir: out

toc: true
number-sections: false
bibliography: references.bib  
format:
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm